version: '3'

services:
  app:
    container_name: app_flask
    build:
      context: . 
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: app_redis
    image: redis:latest
    ports:
      - "6379:6379"
